---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: Role
metadata:
  name: bridge-role
  namespace:
rules:
- apiGroups: ["*"]
  resources: ["*"]
  verbs: ["*"]
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: bridge-binding
  namespace:
subjects:
- kind: ServiceAccount
  name: bridge-sa
  namespace: kube-system
roleRef:
  kind: Role
  name: bridge-role
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  labels:
    name: device-plugin-network-bridge
  name: device-plugin-network-bridge
  namespace: kube-system
spec:
  selector:
    matchLabels:
      name: device-plugin-network-bridge
  template:
    metadata:
      labels:
        name: device-plugin-network-bridge
    spec:
      serviceAccountName: bridge-sa
      hostNetwork: true
      hostPID: true
      containers:
      - name: device-plugin-network-bridge
        image: quay.io/kubevirt/device-plugin-network-bridge:latest
        securityContext:
          privileged: true
        volumeMounts:
          - name: var-run
            mountPath: /var/run
          - name: device-plugin
            mountPath: /var/lib/kubelet/device-plugins
      volumes:
        - name: var-run
          hostPath:
            path: /var/run
        - name: device-plugin
          hostPath:
            path: /var/lib/kubelet/device-plugins
